### ISSUE TITLE
Aplikace ujíždí.

### ISSUE THREAD

**Issue by grizllym** [grizllym/NUR_2#3]
Když jsi klikneš do hledání v ORDER a po objevení klávesnice přejdeš na BILL, kde poté klávesnici schováš klávesou zpět, tak celá aplikace ujede nahoru 😆

**Comment by kozajaku** [comment]
Je potřeba tam zavolat funkci `hideKeyboard`, kterou jsem tam přidával při přechodu mezi jednotlivmi taby. Přesun na jiný tab se zřejmě nepočítá jako ztráta focusu na textové pole, takže se klávesnice nevypne. Je to ale spíš takovej workaroud. Takhle ujíždět by to podle mě nemělo ani když je tam ta klávesnice zobrazená.

**Comment by kozajaku** [comment]
Mrknu se na to, až budu mít čas.
